[package]
name = "badchain-bad-addresses"
description = "Types and utilities for the Badchain SlotHashes sysvar."
documentation = "https://docs.rs/solana-slot-hashes"
version = "0.0.1"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
serde = ["dep:serde", "dep:serde_derive", "solana-hash/serde"]
sysvar = ["dep:badchain-sdk-ids", "dep:badchain-sysvar-id"]

[dependencies]
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
solana-hash = { workspace = true, default-features = false }
badchain-sdk-ids = { workspace = true, optional = true }
badchain-sysvar-id = { workspace = true, optional = true }
solana-pubkey = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
solana-sha256-hasher = { workspace = true }
